:Author: zainarsady
:Email:
:Date: 22/01/2025
:Revision: version#
:License: Public Domain

= Project: {HEAT LOCK}

IoT Heat Lock is a system of a smart lock that locks and unlocks based on human presence in a certain room. 

AMG8833 Sensor checks the presence of human in certain room by reading the temperature, if there's anything above 34C the door will (stay) unlock. If there's no one then the door will shut off or locked. 
If a person wants to come in they have to use the keypad and enter the correct password to unlock the door. 

== Step 1: Installation

1. Open this file
2. Download AMG8833 library in arduino IDE (make sure you get the adafruit one!)
3. Edit the file as how you like.
4. Debug if there's any problem.
5. Release to the world!

== Step 2: Assemble the circuit

Just assemble the BOM as how you want, there's no specific things.
Just remember if you mistake the GND and 5V the sensor will be hottt and it might cause a defect. 
Ensure the wiring is correct before any test run!!

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
  this repository                => Arduino sketch folder
  ├── IOT_HEAT_LOCK_jan22a.ino       => main Arduino file
  └── ReadMe.adoc         => this file
....

=== License
This project is released under ZAINPY. 

=== Contributing
To contribute to this project please contact: my discord

=== BOM

|===
| ID | Part name      | Quantity
| S1 | AMG8833        | 1    
| K1 | 3*3 num Keypad | 1   
| A1 | ESP32 DevKit   | 1
| S2 | Servo Motor    | 1

and bunch of jumpwires
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
